--liquibase formatted sql

--changeset kansei:001-create-tailwind-users-table
-- user_id is the shieldwall user id, a plain column and never a FK. A row exists only after the user opts in.
CREATE TABLE tailwind_users (
    user_id UUID PRIMARY KEY,
    joined_at TIMESTAMPTZ NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    default_visibility VARCHAR(16) NOT NULL DEFAULT 'PUBLIC'
);

--changeset kansei:002-create-countries-table
CREATE TABLE countries (
    code VARCHAR(2) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    continent VARCHAR(2) NOT NULL
);

--changeset kansei:003-create-airports-table
-- Loaded once from src/main/resources/db/data/airports.csv when the table is empty, admin-editable after that.
-- icao or iata may be null (some airports have only one), never both.
CREATE TABLE airports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao VARCHAR(4) UNIQUE,
    iata VARCHAR(3) UNIQUE,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255),
    country_code VARCHAR(2) NOT NULL REFERENCES countries (code),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    time_zone VARCHAR(64),
    airport_type VARCHAR(32) NOT NULL,
    CONSTRAINT airports_code_present CHECK (icao IS NOT NULL OR iata IS NOT NULL)
);

--changeset kansei:004-create-airlines-table
-- ICAO is the key (always present for real operators), IATA is nullable and not unique because IATA codes get reused.
CREATE TABLE airlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao VARCHAR(3) NOT NULL UNIQUE,
    iata VARCHAR(2),
    name VARCHAR(255) NOT NULL,
    country_code VARCHAR(2) REFERENCES countries (code),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

--changeset kansei:005-create-aircraft-types-table
-- ICAO type designator based. family groups variants for stats (A320 family, 737), body_type drives the collection cards.
CREATE TABLE aircraft_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao_code VARCHAR(4) NOT NULL UNIQUE,
    manufacturer VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    family VARCHAR(255) NOT NULL,
    body_type VARCHAR(16) NOT NULL,
    engine_type VARCHAR(16) NOT NULL,
    engine_count SMALLINT,
    wake_category VARCHAR(1)
);

--changeset kansei:006-create-aircraft-model-aliases-table
-- Normalized model strings (lowercase, no manufacturer, no punctuation) that resolve to exactly one aircraft type.
-- Seeded from the types on first start, admins add the rest.
CREATE TABLE aircraft_model_aliases (
    alias_key VARCHAR(100) PRIMARY KEY,
    aircraft_type_id BIGINT NOT NULL REFERENCES aircraft_types (id) ON DELETE CASCADE
);

--changeset kansei:007-create-flights-table
-- Canonical flight shared by every user who took it. API rows are unique on flight number + local departure
-- date + departure airport (a number can have several legs), manual rows are private to their one user_flight.
CREATE TABLE flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(8) NOT NULL,
    flight_number VARCHAR(10),
    flight_date DATE NOT NULL,
    airline_id BIGINT NOT NULL REFERENCES airlines (id),
    departure_airport_id BIGINT NOT NULL REFERENCES airports (id),
    arrival_airport_id BIGINT NOT NULL REFERENCES airports (id),
    status VARCHAR(32),
    is_cargo BOOLEAN NOT NULL DEFAULT FALSE,
    aircraft_type_id BIGINT REFERENCES aircraft_types (id),
    aircraft_family VARCHAR(255),
    aircraft_model_raw VARCHAR(255),
    registration VARCHAR(16),
    mode_s VARCHAR(8),
    departure_scheduled_utc TIMESTAMPTZ,
    departure_revised_utc TIMESTAMPTZ,
    departure_actual_utc TIMESTAMPTZ,
    arrival_scheduled_utc TIMESTAMPTZ,
    arrival_revised_utc TIMESTAMPTZ,
    arrival_actual_utc TIMESTAMPTZ,
    distance_km DOUBLE PRECISION NOT NULL,
    api_payload JSONB,
    api_last_updated_utc TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX flights_api_unique ON flights (flight_number, flight_date, departure_airport_id) WHERE source = 'API';
CREATE INDEX flights_number_date ON flights (flight_number, flight_date);

--changeset kansei:008-create-journeys-and-user-flights-tables
-- user_id is the shieldwall user id, a plain column and never a FK. A journey groups flights and has no visibility,
-- each user_flight carries its own. Order inside a journey is chronological, derived, not stored.
CREATE TABLE journeys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    title VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX journeys_user ON journeys (user_id);

CREATE TABLE user_flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    journey_id BIGINT NOT NULL REFERENCES journeys (id) ON DELETE CASCADE,
    flight_id BIGINT NOT NULL REFERENCES flights (id),
    visibility VARCHAR(16) NOT NULL,
    seat VARCHAR(8),
    seat_position VARCHAR(16),
    cabin_class VARCHAR(24),
    reason VARCHAR(16),
    stop_type VARCHAR(24),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT user_flights_user_flight_unique UNIQUE (user_id, flight_id)
);
CREATE INDEX user_flights_journey ON user_flights (journey_id);
CREATE INDEX user_flights_user ON user_flights (user_id);

--changeset kansei:009-create-aircraft-photos-table
-- One representative photo per aircraft type. The file lives under the storage root, only the pointer and
-- the attribution live here. origin says whether an admin picked it from Wikimedia Commons or uploaded it.
CREATE TABLE aircraft_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_type_id BIGINT NOT NULL UNIQUE REFERENCES aircraft_types (id) ON DELETE CASCADE,
    file_name VARCHAR(100) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    origin VARCHAR(16) NOT NULL,
    title VARCHAR(500),
    author VARCHAR(500),
    license VARCHAR(255),
    source_url VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL
);
