--liquibase formatted sql

--changeset kansei:001-create-tailwind-users-table
-- user_id is the shieldwall user id, a plain column and never a FK. A row exists only after the user opts in.
CREATE TABLE tailwind_users (
    user_id UUID PRIMARY KEY,
    joined_at TIMESTAMPTZ NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    default_visibility VARCHAR(16) NOT NULL DEFAULT 'PUBLIC'
);

--changeset kansei:002-create-countries-table
CREATE TABLE countries (
    code VARCHAR(2) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    continent VARCHAR(2) NOT NULL
);

--changeset kansei:003-create-airports-table
-- Loaded once from src/main/resources/db/data/airports.csv when the table is empty, admin-editable after that.
-- icao or iata may be null (some airports have only one), never both.
CREATE TABLE airports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao VARCHAR(4) UNIQUE,
    iata VARCHAR(3) UNIQUE,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255),
    country_code VARCHAR(2) NOT NULL REFERENCES countries (code),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    time_zone VARCHAR(64),
    airport_type VARCHAR(32) NOT NULL,
    CONSTRAINT airports_code_present CHECK (icao IS NOT NULL OR iata IS NOT NULL)
);

--changeset kansei:004-create-airlines-table
-- ICAO is the key (always present for real operators), IATA is nullable and not unique because IATA codes get reused.
CREATE TABLE airlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao VARCHAR(3) NOT NULL UNIQUE,
    iata VARCHAR(2),
    name VARCHAR(255) NOT NULL,
    country_code VARCHAR(2) REFERENCES countries (code),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

--changeset kansei:005-create-aircraft-types-table
-- ICAO type designator based. family groups variants for stats (A320 family, 737), body_type drives the collection cards.
CREATE TABLE aircraft_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao_code VARCHAR(4) NOT NULL UNIQUE,
    manufacturer VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    family VARCHAR(255) NOT NULL,
    body_type VARCHAR(16) NOT NULL,
    engine_type VARCHAR(16) NOT NULL,
    engine_count SMALLINT,
    wake_category VARCHAR(1)
);
