// Reads .env and writes src/app/core/config.ts, run automatically before start/build (see package.json).
// config.ts itself is gitignored, this script is the only thing that generates it.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'src', 'app', 'core', 'config.ts');
const REQUIRED_KEYS = ['CONTROL_TOWER_URL', 'NORTHSTAR_URL'];

if (!fs.existsSync(envPath)) {
  console.error(`Missing ${envPath}, copy .env.example to .env and fill in real values.`);
  process.exit(1);
}

const env = {};
for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eq = trimmed.indexOf('=');
  if (eq === -1) continue;
  env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
}

const missing = REQUIRED_KEYS.filter((key) => !env[key]);
if (missing.length > 0) {
  console.error(`Missing ${missing.join(', ')} in ${envPath}`);
  process.exit(1);
}

const body = [
  '// Generated by scripts/generate-config.js from .env, do not edit directly, do not commit',
  ...REQUIRED_KEYS.map((key) => `export const ${key} = '${env[key]}';`),
  '',
].join('\n');

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, body);
console.log(`Wrote ${outPath}`);
